"""empty message

Revision ID: b84af8ae5c69
Revises: 9362f060b4df
Create Date: 2023-07-12 21:52:26.767290

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b84af8ae5c69'
down_revision = '9362f060b4df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=255), nullable=True))
        batch_op.drop_index('username')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('first_name', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('last_name', mysql.VARCHAR(length=255), nullable=False))
        batch_op.create_index('username', ['username'], unique=False)
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
